// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/configuration/configuration.proto

package configuration

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigurationStatus struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated              bool     `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted              bool     `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigurationStatus) Reset()         { *m = ConfigurationStatus{} }
func (m *ConfigurationStatus) String() string { return proto.CompactTextString(m) }
func (*ConfigurationStatus) ProtoMessage()    {}
func (*ConfigurationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_edff19f92b198a8f, []int{0}
}

func (m *ConfigurationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationStatus.Unmarshal(m, b)
}
func (m *ConfigurationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationStatus.Marshal(b, m, deterministic)
}
func (m *ConfigurationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationStatus.Merge(m, src)
}
func (m *ConfigurationStatus) XXX_Size() int {
	return xxx_messageInfo_ConfigurationStatus.Size(m)
}
func (m *ConfigurationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationStatus proto.InternalMessageInfo

func (m *ConfigurationStatus) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *ConfigurationStatus) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *ConfigurationStatus) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type ConfigurationClient struct {
	ConfigClientId       int64    `protobuf:"varint,1,opt,name=config_client_id,json=configClientId,proto3" json:"config_client_id,omitempty"`
	ConfigClientUuid     string   `protobuf:"bytes,2,opt,name=config_client_uuid,json=configClientUuid,proto3" json:"config_client_uuid,omitempty"`
	MultipleLanguageId   int32    `protobuf:"varint,3,opt,name=multiple_language_id,json=multipleLanguageId,proto3" json:"multiple_language_id,omitempty"`
	Appname              string   `protobuf:"bytes,4,opt,name=appname,proto3" json:"appname,omitempty"`
	ReportTitle          string   `protobuf:"bytes,5,opt,name=report_title,json=reportTitle,proto3" json:"report_title,omitempty"`
	CompanySubsId        string   `protobuf:"bytes,6,opt,name=company_subs_id,json=companySubsId,proto3" json:"company_subs_id,omitempty"`
	IsConfigDeleted      int32    `protobuf:"varint,7,opt,name=is_config_deleted,json=isConfigDeleted,proto3" json:"is_config_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigurationClient) Reset()         { *m = ConfigurationClient{} }
func (m *ConfigurationClient) String() string { return proto.CompactTextString(m) }
func (*ConfigurationClient) ProtoMessage()    {}
func (*ConfigurationClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_edff19f92b198a8f, []int{1}
}

func (m *ConfigurationClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationClient.Unmarshal(m, b)
}
func (m *ConfigurationClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationClient.Marshal(b, m, deterministic)
}
func (m *ConfigurationClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationClient.Merge(m, src)
}
func (m *ConfigurationClient) XXX_Size() int {
	return xxx_messageInfo_ConfigurationClient.Size(m)
}
func (m *ConfigurationClient) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationClient.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationClient proto.InternalMessageInfo

func (m *ConfigurationClient) GetConfigClientId() int64 {
	if m != nil {
		return m.ConfigClientId
	}
	return 0
}

func (m *ConfigurationClient) GetConfigClientUuid() string {
	if m != nil {
		return m.ConfigClientUuid
	}
	return ""
}

func (m *ConfigurationClient) GetMultipleLanguageId() int32 {
	if m != nil {
		return m.MultipleLanguageId
	}
	return 0
}

func (m *ConfigurationClient) GetAppname() string {
	if m != nil {
		return m.Appname
	}
	return ""
}

func (m *ConfigurationClient) GetReportTitle() string {
	if m != nil {
		return m.ReportTitle
	}
	return ""
}

func (m *ConfigurationClient) GetCompanySubsId() string {
	if m != nil {
		return m.CompanySubsId
	}
	return ""
}

func (m *ConfigurationClient) GetIsConfigDeleted() int32 {
	if m != nil {
		return m.IsConfigDeleted
	}
	return 0
}

type RequestConfigCient struct {
	Configclient         *ConfigurationClient `protobuf:"bytes,1,opt,name=configclient,proto3" json:"configclient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestConfigCient) Reset()         { *m = RequestConfigCient{} }
func (m *RequestConfigCient) String() string { return proto.CompactTextString(m) }
func (*RequestConfigCient) ProtoMessage()    {}
func (*RequestConfigCient) Descriptor() ([]byte, []int) {
	return fileDescriptor_edff19f92b198a8f, []int{2}
}

func (m *RequestConfigCient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConfigCient.Unmarshal(m, b)
}
func (m *RequestConfigCient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConfigCient.Marshal(b, m, deterministic)
}
func (m *RequestConfigCient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConfigCient.Merge(m, src)
}
func (m *RequestConfigCient) XXX_Size() int {
	return xxx_messageInfo_RequestConfigCient.Size(m)
}
func (m *RequestConfigCient) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConfigCient.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConfigCient proto.InternalMessageInfo

func (m *RequestConfigCient) GetConfigclient() *ConfigurationClient {
	if m != nil {
		return m.Configclient
	}
	return nil
}

type ResponseConfigClient struct {
	Status               *ConfigurationStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Configclient         *ConfigurationClient   `protobuf:"bytes,2,opt,name=configclient,proto3" json:"configclient,omitempty"`
	Configclients        []*ConfigurationClient `protobuf:"bytes,3,rep,name=configclients,proto3" json:"configclients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ResponseConfigClient) Reset()         { *m = ResponseConfigClient{} }
func (m *ResponseConfigClient) String() string { return proto.CompactTextString(m) }
func (*ResponseConfigClient) ProtoMessage()    {}
func (*ResponseConfigClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_edff19f92b198a8f, []int{3}
}

func (m *ResponseConfigClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseConfigClient.Unmarshal(m, b)
}
func (m *ResponseConfigClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseConfigClient.Marshal(b, m, deterministic)
}
func (m *ResponseConfigClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseConfigClient.Merge(m, src)
}
func (m *ResponseConfigClient) XXX_Size() int {
	return xxx_messageInfo_ResponseConfigClient.Size(m)
}
func (m *ResponseConfigClient) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseConfigClient.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseConfigClient proto.InternalMessageInfo

func (m *ResponseConfigClient) GetStatus() *ConfigurationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ResponseConfigClient) GetConfigclient() *ConfigurationClient {
	if m != nil {
		return m.Configclient
	}
	return nil
}

func (m *ResponseConfigClient) GetConfigclients() []*ConfigurationClient {
	if m != nil {
		return m.Configclients
	}
	return nil
}

type ConfigurationGlobal struct {
	ConfigGlobalId       int32    `protobuf:"varint,1,opt,name=config_global_id,json=configGlobalId,proto3" json:"config_global_id,omitempty"`
	Footertext           string   `protobuf:"bytes,2,opt,name=footertext,proto3" json:"footertext,omitempty"`
	ServerSmpt           string   `protobuf:"bytes,3,opt,name=server_smpt,json=serverSmpt,proto3" json:"server_smpt,omitempty"`
	Ssl                  bool     `protobuf:"varint,4,opt,name=ssl,proto3" json:"ssl,omitempty"`
	Port                 int64    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	IsAuth               bool     `protobuf:"varint,6,opt,name=is_auth,json=isAuth,proto3" json:"is_auth,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	IsActive             bool     `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigurationGlobal) Reset()         { *m = ConfigurationGlobal{} }
func (m *ConfigurationGlobal) String() string { return proto.CompactTextString(m) }
func (*ConfigurationGlobal) ProtoMessage()    {}
func (*ConfigurationGlobal) Descriptor() ([]byte, []int) {
	return fileDescriptor_edff19f92b198a8f, []int{4}
}

func (m *ConfigurationGlobal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationGlobal.Unmarshal(m, b)
}
func (m *ConfigurationGlobal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationGlobal.Marshal(b, m, deterministic)
}
func (m *ConfigurationGlobal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationGlobal.Merge(m, src)
}
func (m *ConfigurationGlobal) XXX_Size() int {
	return xxx_messageInfo_ConfigurationGlobal.Size(m)
}
func (m *ConfigurationGlobal) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationGlobal.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationGlobal proto.InternalMessageInfo

func (m *ConfigurationGlobal) GetConfigGlobalId() int32 {
	if m != nil {
		return m.ConfigGlobalId
	}
	return 0
}

func (m *ConfigurationGlobal) GetFootertext() string {
	if m != nil {
		return m.Footertext
	}
	return ""
}

func (m *ConfigurationGlobal) GetServerSmpt() string {
	if m != nil {
		return m.ServerSmpt
	}
	return ""
}

func (m *ConfigurationGlobal) GetSsl() bool {
	if m != nil {
		return m.Ssl
	}
	return false
}

func (m *ConfigurationGlobal) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ConfigurationGlobal) GetIsAuth() bool {
	if m != nil {
		return m.IsAuth
	}
	return false
}

func (m *ConfigurationGlobal) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ConfigurationGlobal) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ConfigurationGlobal) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type RequestConfigGlobal struct {
	Configglobal         *ConfigurationGlobal `protobuf:"bytes,1,opt,name=configglobal,proto3" json:"configglobal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestConfigGlobal) Reset()         { *m = RequestConfigGlobal{} }
func (m *RequestConfigGlobal) String() string { return proto.CompactTextString(m) }
func (*RequestConfigGlobal) ProtoMessage()    {}
func (*RequestConfigGlobal) Descriptor() ([]byte, []int) {
	return fileDescriptor_edff19f92b198a8f, []int{5}
}

func (m *RequestConfigGlobal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConfigGlobal.Unmarshal(m, b)
}
func (m *RequestConfigGlobal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConfigGlobal.Marshal(b, m, deterministic)
}
func (m *RequestConfigGlobal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConfigGlobal.Merge(m, src)
}
func (m *RequestConfigGlobal) XXX_Size() int {
	return xxx_messageInfo_RequestConfigGlobal.Size(m)
}
func (m *RequestConfigGlobal) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConfigGlobal.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConfigGlobal proto.InternalMessageInfo

func (m *RequestConfigGlobal) GetConfigglobal() *ConfigurationGlobal {
	if m != nil {
		return m.Configglobal
	}
	return nil
}

type ResponseConfigGlobal struct {
	Configstatus         *ConfigurationStatus   `protobuf:"bytes,1,opt,name=configstatus,proto3" json:"configstatus,omitempty"`
	Configglobal         *ConfigurationGlobal   `protobuf:"bytes,2,opt,name=configglobal,proto3" json:"configglobal,omitempty"`
	Configglobals        []*ConfigurationGlobal `protobuf:"bytes,3,rep,name=configglobals,proto3" json:"configglobals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ResponseConfigGlobal) Reset()         { *m = ResponseConfigGlobal{} }
func (m *ResponseConfigGlobal) String() string { return proto.CompactTextString(m) }
func (*ResponseConfigGlobal) ProtoMessage()    {}
func (*ResponseConfigGlobal) Descriptor() ([]byte, []int) {
	return fileDescriptor_edff19f92b198a8f, []int{6}
}

func (m *ResponseConfigGlobal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseConfigGlobal.Unmarshal(m, b)
}
func (m *ResponseConfigGlobal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseConfigGlobal.Marshal(b, m, deterministic)
}
func (m *ResponseConfigGlobal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseConfigGlobal.Merge(m, src)
}
func (m *ResponseConfigGlobal) XXX_Size() int {
	return xxx_messageInfo_ResponseConfigGlobal.Size(m)
}
func (m *ResponseConfigGlobal) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseConfigGlobal.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseConfigGlobal proto.InternalMessageInfo

func (m *ResponseConfigGlobal) GetConfigstatus() *ConfigurationStatus {
	if m != nil {
		return m.Configstatus
	}
	return nil
}

func (m *ResponseConfigGlobal) GetConfigglobal() *ConfigurationGlobal {
	if m != nil {
		return m.Configglobal
	}
	return nil
}

func (m *ResponseConfigGlobal) GetConfigglobals() []*ConfigurationGlobal {
	if m != nil {
		return m.Configglobals
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigurationStatus)(nil), "configuration.ConfigurationStatus")
	proto.RegisterType((*ConfigurationClient)(nil), "configuration.ConfigurationClient")
	proto.RegisterType((*RequestConfigCient)(nil), "configuration.RequestConfigCient")
	proto.RegisterType((*ResponseConfigClient)(nil), "configuration.ResponseConfigClient")
	proto.RegisterType((*ConfigurationGlobal)(nil), "configuration.ConfigurationGlobal")
	proto.RegisterType((*RequestConfigGlobal)(nil), "configuration.RequestConfigGlobal")
	proto.RegisterType((*ResponseConfigGlobal)(nil), "configuration.ResponseConfigGlobal")
}

func init() {
	proto.RegisterFile("proto/configuration/configuration.proto", fileDescriptor_edff19f92b198a8f)
}

var fileDescriptor_edff19f92b198a8f = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdf, 0x4e, 0xd4, 0x4e,
	0x14, 0x86, 0x5d, 0xd8, 0x3f, 0x07, 0xf8, 0xc1, 0x6f, 0x20, 0x58, 0xd1, 0x08, 0xd4, 0x44, 0x89,
	0x31, 0x68, 0xf0, 0xce, 0x3b, 0x58, 0x22, 0x6e, 0xe2, 0xd5, 0xac, 0xdc, 0x69, 0x6a, 0xb7, 0x1d,
	0x96, 0x09, 0xdd, 0xb6, 0x76, 0x66, 0x50, 0xde, 0xc3, 0x07, 0xf1, 0xa1, 0x7c, 0x00, 0x6f, 0xbc,
	0x37, 0x3d, 0xa7, 0xc5, 0xed, 0xb6, 0xd1, 0x95, 0x54, 0xee, 0xf6, 0x9c, 0xef, 0x9c, 0xf3, 0x9d,
	0xf9, 0xfa, 0xcd, 0x00, 0x3c, 0x8e, 0x93, 0x48, 0x47, 0xcf, 0xbc, 0x28, 0x3c, 0x93, 0x23, 0x93,
	0xb8, 0x5a, 0x46, 0x61, 0x31, 0xda, 0xc7, 0x0a, 0xb6, 0x52, 0x48, 0xda, 0x1e, 0xac, 0xf7, 0x26,
	0x13, 0x03, 0xed, 0x6a, 0xa3, 0x98, 0x05, 0x6d, 0x2f, 0x11, 0xae, 0x16, 0xbe, 0x35, 0xbf, 0x33,
	0xbf, 0xd7, 0xe1, 0x79, 0x98, 0x22, 0x26, 0xf6, 0x11, 0x69, 0x10, 0x92, 0x85, 0x29, 0xe2, 0x8b,
	0x40, 0xa4, 0x48, 0x93, 0x90, 0x2c, 0xb4, 0xbf, 0x36, 0xa6, 0x58, 0x7a, 0x81, 0x14, 0xa1, 0x66,
	0x7b, 0xb0, 0x46, 0xdb, 0x38, 0x1e, 0x26, 0x1c, 0x49, 0x74, 0x4d, 0xfe, 0x1f, 0xe5, 0xa9, 0xae,
	0xef, 0xb3, 0xa7, 0xc0, 0x8a, 0x95, 0xc6, 0x48, 0x5a, 0xa0, 0xcb, 0xd7, 0x26, 0x6b, 0x4f, 0x8d,
	0xf4, 0xd9, 0x73, 0xd8, 0x18, 0x9b, 0x40, 0xcb, 0x38, 0x10, 0x4e, 0xe0, 0x86, 0x23, 0xe3, 0x8e,
	0x44, 0x3a, 0x3b, 0x5d, 0x6b, 0x91, 0xb3, 0x1c, 0x7b, 0x93, 0x41, 0x7d, 0xdc, 0xdd, 0x8d, 0xe3,
	0xd0, 0x1d, 0x0b, 0x6b, 0x01, 0x87, 0xe6, 0x21, 0xdb, 0x85, 0xe5, 0x44, 0xc4, 0x51, 0xa2, 0x1d,
	0x2d, 0x75, 0x20, 0xac, 0x45, 0x84, 0x97, 0x28, 0xf7, 0x36, 0x4d, 0xb1, 0x47, 0xb0, 0xea, 0x45,
	0xe3, 0xd8, 0x0d, 0xaf, 0x1c, 0x65, 0x86, 0x2a, 0x65, 0x6a, 0x61, 0xd5, 0x4a, 0x96, 0x1e, 0x98,
	0xa1, 0xea, 0xfb, 0xec, 0x09, 0xfc, 0x2f, 0x95, 0x93, 0x9d, 0x23, 0x97, 0xaa, 0x8d, 0x3b, 0xad,
	0x4a, 0x45, 0x02, 0x1d, 0x67, 0x92, 0xbd, 0x03, 0xc6, 0xc5, 0x47, 0x23, 0x94, 0xa6, 0x7c, 0x0f,
	0x05, 0x7b, 0x05, 0xcb, 0xd4, 0x4e, 0x2a, 0xa0, 0x58, 0x4b, 0x07, 0xf6, 0x7e, 0xf1, 0x43, 0x57,
	0x48, 0xcd, 0x0b, 0x7d, 0xf6, 0xb7, 0x79, 0xd8, 0xe0, 0x42, 0xc5, 0x51, 0xa8, 0x44, 0x6f, 0x42,
	0x3d, 0xf6, 0x12, 0x5a, 0x0a, 0x1d, 0x30, 0xcb, 0x68, 0xf2, 0x0a, 0xcf, 0x3a, 0x4a, 0xcb, 0x35,
	0x6e, 0xb6, 0x1c, 0x7b, 0x0d, 0x2b, 0x93, 0xb1, 0xb2, 0x9a, 0x3b, 0xcd, 0x19, 0x07, 0x15, 0x1b,
	0xed, 0x2f, 0xd3, 0xbe, 0x3b, 0x09, 0xa2, 0xa1, 0x1b, 0x4c, 0xf8, 0x6e, 0x84, 0x89, 0xdc, 0x77,
	0x8b, 0xb9, 0xef, 0xa8, 0xae, 0xef, 0xb3, 0x07, 0x00, 0x67, 0x51, 0xa4, 0x45, 0xa2, 0xc5, 0x67,
	0x9d, 0xf9, 0x6d, 0x22, 0xc3, 0xb6, 0x61, 0x49, 0x89, 0xe4, 0x52, 0x24, 0x8e, 0x1a, 0xc7, 0x1a,
	0x0d, 0xd6, 0xe5, 0x40, 0xa9, 0xc1, 0x38, 0xd6, 0x6c, 0x0d, 0x9a, 0x4a, 0x05, 0x68, 0xaa, 0x0e,
	0x4f, 0x7f, 0x32, 0x06, 0x0b, 0xa9, 0x75, 0xd0, 0x48, 0x4d, 0x8e, 0xbf, 0xd9, 0x1d, 0x68, 0x4b,
	0xe5, 0xb8, 0x46, 0x9f, 0xa3, 0x73, 0x3a, 0xbc, 0x25, 0xd5, 0xa1, 0xd1, 0xe7, 0x6c, 0x0b, 0x3a,
	0x46, 0x89, 0x04, 0x8d, 0xd9, 0xc6, 0xe1, 0xd7, 0x71, 0x8a, 0xc5, 0xae, 0x52, 0x9f, 0xa2, 0xc4,
	0xb7, 0x3a, 0x84, 0xe5, 0x31, 0xbb, 0x07, 0xdd, 0x74, 0xa0, 0xa7, 0xe5, 0xa5, 0xb0, 0xba, 0x38,
	0xb2, 0x23, 0xd5, 0x21, 0xc6, 0xf6, 0x7b, 0x58, 0x2f, 0x78, 0x2b, 0x53, 0xe5, 0xfa, 0xfb, 0x91,
	0x28, 0xb3, 0x38, 0x80, 0x3a, 0x79, 0xa1, 0xcf, 0xfe, 0x5e, 0x32, 0xd7, 0x34, 0xc1, 0x5f, 0x5b,
	0xac, 0xd0, 0x57, 0x5a, 0xb4, 0x71, 0xb3, 0x45, 0x7f, 0x19, 0x8d, 0xe2, 0x99, 0x8c, 0x96, 0x0d,
	0x2a, 0x36, 0x1e, 0xfc, 0xe8, 0xc2, 0x46, 0x71, 0x6f, 0x91, 0x5c, 0x4a, 0x4f, 0xb0, 0x21, 0x6c,
	0x9e, 0x08, 0x5d, 0xf5, 0xf6, 0xed, 0x4e, 0xb1, 0x94, 0x6f, 0xfb, 0xd6, 0xc3, 0x52, 0x49, 0xf9,
	0xc6, 0xda, 0x73, 0xec, 0x1c, 0xee, 0x57, 0x73, 0x1c, 0xe1, 0xc3, 0x53, 0x23, 0xd3, 0x10, 0x36,
	0x0f, 0x7d, 0xff, 0xdf, 0x9e, 0xe6, 0x02, 0xb6, 0x4f, 0xf1, 0x0f, 0xca, 0x6d, 0x1c, 0xe8, 0x02,
	0xb6, 0xe9, 0xc1, 0xbd, 0x0d, 0x32, 0xaf, 0xac, 0x5e, 0x76, 0x31, 0xec, 0xdf, 0x71, 0x50, 0xcd,
	0x1f, 0x48, 0xa8, 0xc8, 0x9e, 0x63, 0x67, 0x70, 0xb7, 0x42, 0xbe, 0xfa, 0x79, 0x3e, 0xc0, 0x7a,
	0x85, 0x72, 0x75, 0x32, 0x78, 0xe5, 0xab, 0x53, 0xff, 0x31, 0x46, 0xb0, 0x55, 0x4d, 0x72, 0x74,
	0xd5, 0x3f, 0xae, 0x93, 0x48, 0x96, 0x2f, 0x29, 0x61, 0xf4, 0x26, 0xd7, 0x4c, 0x35, 0xb8, 0x1d,
	0xaa, 0x61, 0x0b, 0xff, 0xa7, 0x7c, 0xf1, 0x33, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x17, 0x4c, 0xf5,
	0x7e, 0x0a, 0x00, 0x00,
}
